### ISSUE TITLE
Week 4 Accounts and Logins

### ISSUE THREAD

**Issue by Isaac-Le** [Isaac-Le/Tri3Repo#7]
CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)

- [ ] CB Create Task Coding requirements documented

- [ ] Runtime of Code(with comments) on Replit/Intellij
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [ ] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [ ] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [ ] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [ ] Hack #2 Add logout to CRUD screen
- [ ] Hack #3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by jeankim05** [comment]
**Jean's Grade for Isaac - 5/5**

CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)

 CB Create Task Coding requirements documented
https://isaac-le.github.io/Tri3Repo/createtask
 Runtime of Code(with comments) on Replit/Intellij
https://isaac-le.github.io/Tri3Repo/createtask
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)

 Hack 1 Add Phone Number to Sign Up / Authorization screen
https://github.com/Paul-D6/nighthawk_csp/blob/master/cruddy/templates/cruddy/authorize.html
https://github.com/Paul-D6/nighthawk_csp/blob/master/cruddy/query.py
 Hack 2 Add logout to CRUD screen
https://github.com/Paul-D6/nighthawk_csp/blob/master/cruddy/query.py
https://github.com/Paul-D6/nighthawk_csp/blob/master/cruddy/templates/cruddy/crud.html
 Hack 3 Add login_required to another portion of the project
https://github.com/Paul-D6/nighthawk_csp/blob/master/frontend/frontend.py
